name: update-prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - uses: hashicorp/setup-terraform@v2.0.3 # https://github.com/hashicorp/setup-terraform/releases
        with:
          terraform_version: 1.3.6 # https://github.com/hashicorp/terraform/releases
          terraform_wrapper: false
      - name: init
        run: terraform init
      - name: validate
        run: terraform validate
      - name: plan
        run: terraform plan -out=tfplan
      - name: apply
        run: terraform apply -auto-approve tfplan
      - name: check
        run: terraform plan -detailed-exitcode